<!-- Get PHP Utils -->
<?php require '../scripts/utils.php'; ?>

<?php pageHeader("..", "Welcome"); ?>
<?php subPageTop(); ?>

    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
    <p>Welcome -- TEST</p>
<?php echo subPageBottom();?>